### ISSUE TITLE
Version 2.1 causes random fluctuations in brightness for external display.

### ISSUE THREAD

**Issue by rsaid99** [OCJvanDijk/Brightness-Sync#10]
Reverted back to previous version and issue went away.

Running on a 2018 MacBook Pro with 5K Ultrafine.

**Comment by OCJvanDijk** [comment]
Thanks for reporting. Are they fast fluctuations like a flicker? Do you have a Brightness Offset set?

**Comment by rsaid99** [comment]
Yes, they are very slight but perceptible changes to the brightness, almost like someone is wiggling the cable in the back of an old monitor :)  I use the offset feature, and had it set to the same value for weeks leading up to the upgrade to 2.1

**Comment by OCJvanDijk** [comment]
Ah ok. I should have seen that coming. The offset feature was implemented as a workaround for a problem in v1 and is kind of broken in v2. The flicker might occur in 2.0 but only occasionally when the brightness changes. In 2.1 it syncs continuously so the flicker might occur continuously. I don’t use the offset feature, so I didn’t think about it nor test it. I was actually considering removing it altogether. I’m curious about your use case for it?

**Comment by rsaid99** [comment]
I was thrilled when the offset feature was added because I was really wanting it at the time.  The use case is slightly differing levels of brightness needs between the built-in display and the external display.  My laptop sits to the right of my large screen and sits at a 45 degree angle.  So the light coming through the window hits each display at a different angle.  Having the offset allows me to perfectly tune for the situation without losing it when the brightness changes.  The only other feature that would complete this app for me is to have my bluetooth keyboard brightness controls *only* affect the offset rather than both screens.  But I digress -- please know that the offset is valuable!

**Comment by OCJvanDijk** [comment]
I released a new version with a fix for the issue. Let me know if you experience any more problems. It also calculates offset a bit differently, but this should be for the better.

Thinking further about the use case for this feature, it should also be possible to set different offsets for different monitors, in case you have multiple UltraFines. I also like the idea of being able to control the offset with your keyboard, so I came up with an idea to hit two birds with one stone: instead of controlling the offset with a slider in the menu, the app could capture any changes you make to your external monitor’s brightness while the app is running and treat them as setting an offset. In practice this means you can control the offset directly from a Touch Bar, by ctrl pressing the brightness keys on a keyboard, or any other way you can normally control an external monitor’s brightness.

I already got this running on my machine and it seems to be working pretty well, but it needs more time to cook. This brightness stuff is finicky and hard to test... Maybe I’ll release it as a beta version first this time.

**Comment by OCJvanDijk** [comment]
@rsaid99 Check out the new version for controlling offset with your keyboard!
