### ISSUE TITLE
Discrepancy of brightness between build-in display and monitor

### ISSUE THREAD

**Issue by Heheovereggs** [OCJvanDijk/Brightness-Sync#13]
When I run this application the brightness of the monitor is always a little bit lower than my macbook, therefore the brightness of the monitor couldn't reach the highest value.

The model of my 2019 MacBook pro with 2 Thunderbolt ports mac is A2159, and the model of my 22-inch LG Ultrafine monitor is 22MD4KA. My system version is 10.15.4. 
The app versions I had tried are 2.1.1 and 2.2.0.

Here's the brightness shown in touch bar.
<img width="1085" alt="觸控列快照 2020-05-10 上午11 51 37" src="https://user-images.githubusercontent.com/63461260/81503961-9df3f180-92b4-11ea-8eac-0a1c13e3ad8d.png">

Thank you!

**Comment by OCJvanDijk** [comment]
The app is designed to match the actual physical brightness of your monitors, so they will look the same to the eye. The sliders work differently for different monitors, so they may not match. You can try setting the sliders manually to the same level without the app and observe that your external monitor will be brighter that way.

You are correct that your LG will never reach its maximum brightness. This is by design, because that would mean it would be brighter than your built-in display. The built-in display just has a lower maximum brightness than the LG.

Personally I like my monitors to match exactly all the time, but I do get that others may want all displays to be as bright as possible when working in a very bright environment, even if that means that one will be brighter than the other. Unfortunately, the only way to achieve that right now is to set the manual offset. It's just a limitation of the whole brightness synchronization solution this app employs.
