### ISSUE TITLE
Brightness offset option

### ISSUE THREAD

**Issue by matej** [OCJvanDijk/Brightness-Sync#4]
I noticed that when syncing values from mb MBP to the LG the apparent brightness differs a bit. I assume that's because the two displays have different ranges. 

I did a quick addition to the app and added a slider that allows me to tweak the synchronization a bit. Needs a bit more testing, but if anybody else is interested, I could clean this up a bit further and open a PR. https://github.com/matej/Brightness-Sync/commit/fc0890bc7d9053554716334e4691f422da20b071

<img width="242" alt="Screenshot 2019-10-14 at 12 43 21" src="https://user-images.githubusercontent.com/91322/66745815-57562a00-ee80-11e9-9d3b-e272c55bdf9d.png">

**Comment by mustdobetter** [comment]
Thanks @matej  - I literally did exactly the same thing yesterday! This seems to have been more prominent in MacOS Catalina - have you noticed the same? I'll check yours out but doubt my code has anything to add over what you've already done.

<img width="194" alt="Screenshot 2019-10-14 at 12 01 46" src="https://user-images.githubusercontent.com/1746353/66746725-7c479e80-ee7a-11e9-9958-01351f48b4b9.png">

**Comment by matej** [comment]
Ha! Great minds think alike. :) 

I always noticed a bit of a difference, but it's true that it only really started bothering me when I updated to Catalina. So there might be something to it. 

Feel free to tweak my code whatever way you want, or roll your own. Was really just a quick 30 minute job.

**Comment by OCJvanDijk** [comment]
Hey,

This looks good, but I'm interested to know more about the brightness difference you are seeing. I personally haven't really noticed it. There was a period during the Catalina betas when the apparent brightness was way off, but that seems to be fixed in the release version, at least for me.

Also, but this might be another issue, when on or near max brightness, the LG is brighter, but I didn't want to artificially bring the maximum brightness of the LG down, even if that means they are out of sync. If you would want to do that, I guess the offset shouldn't be linear, but depend on the brightness level. I'm not near my monitor right now though so I can't check or play with it.

**Comment by OCJvanDijk** [comment]
I realized I didn't really ask any concrete questions. The difference in brightness I saw on the Catalina beta was really quite big, so I guess my question is: does this or my other comment about max brightness sound familiar or is this about a small difference I just hadn't noticed yet? Anyway, if a constant offset solves the problem for you both, I'd be happy to merge a PR.

**Comment by matej** [comment]
For me there was a noticeable difference even when decently away from the maximums. But I don't know if an uniform transformation is enough to sync those up better. That's the main thing why I mentioned that it needs a bit more testing. 

I can try to make some photos, but it might be hard to tell the difference.

**Comment by OCJvanDijk** [comment]
Ok, I just got home and I also clearly see the difference. Surprised I didn't before. It seems that a constant offset is effective in solving the issue, at least to my eye, although I think we have established I'm not the most perceptive 🙃.

**Comment by OCJvanDijk** [comment]
@matej @mustdobetter Check out v2.0.0, offset shouldn't be needed anymore.

**Comment by mustdobetter** [comment]
Thanks @OCJvanDijk. Can you explain what you've done? I see in the code there are some updates to use "Linear" methods?

**Comment by mustdobetter** [comment]
Also, in version 2 the offset is still present in the menu?

**Comment by OCJvanDijk** [comment]
So there are 3 values in CoreDisplay that I found: user brightness, linear brightness, and dynamic linear brightness. I investigated these values before on Mojave but something seems to have changed in Catalina. Their exact meaning still is confusing to me, but through experimentation I basically found linear brightness to be the one we need.

The offset slider is still there if you need it for some reason, although on second thought, that one now got messed up because it offsets the linear brightness which produces weird results.

**Comment by mustdobetter** [comment]
Thanks, the changes seem to work really well. Since the latest release I now don't notice the brightness change, nor have I felt the need to make any manual adjustments - which is perfect. You know it's working well if you don't notice it at all :)

**Comment by matej** [comment]
Same here. I did not need to use the bigness offset after updating. Good work!
